# Generated by Django 3.2.14 on 2022-07-09 20:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchange',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 21, 51, 51, 838863, tzinfo=utc)),
        ),
    ]
