# Generated by Django 3.2.14 on 2022-07-12 13:01

from django.db import migrations, models
import django_shop.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('short_description', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=8192, null=True)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=13)),
                ('vat_percent', models.IntegerField(default=23)),
                ('currency', models.CharField(default='ZŁ', max_length=6)),
                ('discount_percent', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('available_amount', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('weight_unit', models.CharField(default='g', max_length=6)),
                ('width', models.CharField(max_length=16, null=True)),
                ('height', models.CharField(max_length=16, null=True)),
                ('length', models.CharField(max_length=16, null=True)),
                ('length_unit', models.CharField(default='cm', max_length=6)),
                ('thumb_url', models.URLField(blank=True, null=True)),
                ('image_urls', models.JSONField(default=django_shop.products.models.default_image_urls, null=True)),
                ('recommendations', models.JSONField(default=django_shop.products.models.default_recommendations, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
